
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.168.62.38
    path: "/var/nfs/kubenfs"
